name: escive
description: "A mobile app aiming to be a third-party client for e-scooters with Bluetooth functionality, allowing an alternative interface with more features."
publish_to: 'none'
version: 1.1.0+6

environment:
  sdk: ^3.6.2

dependencies:
  action_slider: 0.8.0-beta.3
  app_links: 6.4.0
  battery_plus: 6.2.1
  crypto: 3.0.6
  cupertino_onboarding: 1.3.0
  easy_localization: 3.0.7+1
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.35.5
  flutter_dotenv: 5.2.1
  flutter_fgbg: 0.7.1
  flutter_native_splash: 2.4.6
  flutter_phoenix: 1.1.1
  geocoding: 4.0.0
  geolocator: 14.0.0
  get_storage: 2.1.1
  haptic_feedback: 0.5.1+1
  http: 1.4.0
  installed_apps: 1.6.0
  intl: 0.20.2
  logarte: 1.0.0
  lucide_icons_flutter: 3.0.3
  mapbox_maps_flutter: 2.9.0
  material_symbols_icons: 4.2815.0
  modal_bottom_sheet: 3.0.0
  native_device_orientation: ^2.0.3
  package_info_plus: 8.3.0
  path_provider: ^2.1.5
  pattern_box: 0.5.4
  permission_handler: 12.0.0+1
  screen_brightness: 2.1.4
  share_plus: 11.0.0
  syncfusion_flutter_gauges: 29.1.38
  system_media_controller: 0.0.2
  universal_io: 2.2.2
  url_launcher: 6.3.1
  uuid: 4.5.1
  volume_controller: 3.4.0
  wakelock_plus: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/
    - resources/langs/
  fonts:
    - family: 'Sora'
      fonts:
        - asset: lib/assets/fonts/Sora/Sora-ExtraBold.ttf
        - asset: lib/assets/fonts/Sora/Sora-Bold.ttf
        - asset: lib/assets/fonts/Sora/Sora-SemiBold.ttf
        - asset: lib/assets/fonts/Sora/Sora-Medium.ttf
        - asset: lib/assets/fonts/Sora/Sora-Regular.ttf
        - asset: lib/assets/fonts/Sora/Sora-Thin.ttf
        - asset: lib/assets/fonts/Sora/Sora-Light.ttf
    - family: 'Inter'
      fonts:
        - asset: lib/assets/fonts/Inter/Inter_28pt-Black.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-BlackItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-ExtraBold.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-ExtraBoldItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Bold.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-BoldItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-SemiBold.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-SemiBoldItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Medium.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-MediumItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Regular.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Italic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Light.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-LightItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-ExtraLight.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-ExtraLightItalic.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-Thin.ttf
        - asset: lib/assets/fonts/Inter/Inter_28pt-ThinItalic.ttf

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  image: lib/assets/logo.png
  color: "#0ECFDC"
  branding: lib/assets/splash_branding.png
  branding_bottom_padding: 24 # the default one is perfect on Android and non-borderless iPhones
  android_12:
    color: "#0ECFDC"
    icon_background_color: "#0ECFDC"
    branding: lib/assets/splash_branding.png